language: bash
sudo: required

env:
  - tf_version=0.12.17

before_install:
  - wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

install:
  - echo 'install'

jobs:
  include:
    - stage: test
      before_script:
        - terraform -v
      script:
        - make test
        - make fmt
